### ISSUE TITLE
[Bug] "Get Involved" button on home page opens "Page not found"

### ISSUE THREAD

**Issue by lixuna** [inclusivenaming/website#40] opened 2021-03-10 16:29 UTC
### [Bug] "Get Involved" button on home page opens "Page not found"
- Issue reported on twitter 

How to recreate: 
- go to https://inclusivenaming.org/ home page
- click on Get Involved button
- I am redirected to https://inclusivenaming.org/get-involved
- I can see an error "Page Not Found, Looks like you've followed a broken link or entered a URL that doesn't exist on this site."

Suggestions:
- update URL for Get Involved button
- change URL from https://inclusivenaming.org/get-involved to https://inclusivenaming.org/participate/

**Comment by wbolster** [comment] 2021-03-11 10:53
see https://twitter.com/inclusivenaming/status/1369946786278825986

the problem is the button, not the menu item:

![image](https://user-images.githubusercontent.com/748944/110776419-55a0b980-8260-11eb-92ec-8b52f4a01d4c.png)

it links to https://inclusivenaming.org/get-involved, which gives:

![image](https://user-images.githubusercontent.com/748944/110776481-67825c80-8260-11eb-9a01-0168291e12c8.png)

**Comment by justaugustus** [comment] 2021-03-15 18:24
@rbowen is taking a look ([ref](https://inclusive-naming.slack.com/archives/C01JCKTUS6M/p1615832572033700)).
Thanks Rich!

**Comment by xmulligan** [comment] 2021-03-16 10:12
We can close this issue now

**Closed** 2021-04-21 20:15 UTC
